Ignore errors when container does not exist.

diff --git a/.github/workflows/deploy-node.yaml b/.github/workflows/deploy-node.yaml
--- a/.github/workflows/deploy-node.yaml
+++ b/.github/workflows/deploy-node.yaml
@@ -26,7 +26,7 @@ jobs:
     needs: build-next-image
     runs-on: ubuntu-latest
     steps:
-      - name: Docker Pull & Run From Hub
+      - name: Deploy New Image and Cleanup
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -35,27 +35,14 @@ jobs:
           script: |
             echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin
             docker pull elarsaks/gorilla-labs-api:${{ github.sha }}
-            # Check if the container is running and stop it
-            if docker ps -q -f name=gorilla-labs-api; then
-                docker stop gorilla-labs-api
-            fi
-            # Check if the container exists and remove it
-            if docker ps -a -q -f name=gorilla-labs-api; then
-                docker rm gorilla-labs-api
-            fi
-            # Run the new gorilla-labs-api container with restart policy, connected to the network
+            # Stop and remove any existing container (ignore errors if not existing)
+            docker stop gorilla-labs-api || true
+            docker rm gorilla-labs-api || true
+            # Run the new container
             docker run -d --restart=always \
               --name gorilla-labs-api \
               --network gorilla-labs-network \
               -p 3000:3000 \
               elarsaks/gorilla-labs-api:${{ github.sha }}
-
-      - name: Cleanup Unused Docker Images
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
-          username: ubuntu
-          script: |
-            # Cleanup unused Docker images to free up space
+            # Cleanup unused Docker images
             docker image prune -af
